# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1db24de18f8adfd5227d0e0d67278e822e509b9d35ff41dcc5d91d69a8c98707fffa4e8ab1080851a2d3446627c2b6e9aba4b672cf1d1528752c794a4c2495c5

test:
  secret_key_base: 84118f448c03f103f7c735351482161b59a024f4b32224daa1a2eb711c200a3b312cbbb97b9587675b5061515baaeff555e0cd4101046487ece02f518fb4ef59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
